name: CI

on:
  push:
    paths-ignore:
      - 'demo/**'
      - 'docker/**'
      - 'Dockerfile'
      - '.dockerignore'
      - '.ghci'
      - '.gitignore'
      - 'images/**'
      - 'notebooks/**'
      - 'README.md'
      - 'hie.yaml'
  pull_request:
    paths-ignore:
      - 'demo/**'
      - 'docker/**'
      - 'Dockerfile'
      - '.dockerignore'
      - '.ghci'
      - '.gitignore'
      - 'images/**'
      - 'notebooks/**'
      - 'README.md'
      - 'hie.yaml'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
        - stack-yaml: 'stack/stack-8.2.yaml'
        - stack-yaml: 'stack/stack-8.4.yaml'
        - stack-yaml: 'stack/stack-8.6.yaml'
        - stack-yaml: 'stack/stack-8.8.yaml'
        - stack-yaml: 'stack/stack-8.10.yaml'
        - stack-yaml: 'stack/stack-9.0.yaml'
        - stack-yaml: 'stack/stack-9.2.yaml'
        - stack-yaml: 'stack/stack-9.4.yaml'
        - stack-yaml: 'stack/stack-9.6.yaml'
        - stack-yaml: 'stack.yaml'

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
        with:
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install

      - uses: haskell/actions/setup@v2
        name: Setup Haskell Stack
        with:
          enable-stack: true
          stack-version: "latest"

      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.versions.stack-yaml }}-${{ hashFiles(format('./{0}', matrix.versions.stack-yaml)) }}

      - name: Build
        export "NIX_PATH=nixpkgs=$(nix run .#print-nixpkgs-master)"
        stack build --nix --stack-yaml ${{matrix.versions.stack-yaml}}

      - name: Test
        export "NIX_PATH=nixpkgs=$(nix run .#print-nixpkgs-master)"
        stack test --nix --stack-yaml ${{matrix.versions.stack-yaml}}

      - name: Run integration test
        # The test is flaky on GHC 8.0 so we don't run it. As long as the tests
        # above pass, it's unlikely that we'll introduce a bug that we will
        # only catch through the integration test on this version and not other
        # versions.
        if: ${{ !contains(fromJSON('["stack-8.0.yaml", "stack-8.2.yaml"]'), matrix.versions.stack-yaml) }}
        run: |
          set -e

          nix build .#jupyterlab
          export PATH="$(pwd)/result/bin:$PATH"
          echo "Got PATH: $PATH"

          stack build --no-terminal
          # Ensure that IHaskell notebook remains unchanged.
          # Run the notebook to regenerate the outputs, then compare the new notebook to the old one.
          stack install
          stack exec -- ihaskell install --stack
          test/acceptance.nbconvert.sh stack exec -- jupyter nbconvert
