name: "Nix"
on:
  schedule:
  - cron: '0 2 * * *'
  push:
    paths-ignore:
    - 'demo/**'
    - 'docker/**'
    - 'Dockerfile'
    - '.dockerignore'
    - '.ghci'
    - '.gitignore'
    - 'images/**'
    - 'notebooks/**'
    - 'README.md'
    - '*.yaml'
  pull_request:
    paths-ignore:
    - 'demo/**'
    - 'docker/**'
    - 'Dockerfile'
    - '.dockerignore'
    - '.ghci'
    - '.gitignore'
    - 'images/**'
    - 'notebooks/**'
    - 'README.md'
    - '*.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        executable:
        - ihaskell-ghc810
        - ihaskell-ghc90
        - ihaskell-ghc92
        - ihaskell-ghc94
        - ihaskell-ghc96
        - ihaskell-ghc98

    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v22
      with:
        install_url: https://releases.nixos.org/nix/nix-2.13.3/install

    - uses: cachix/cachix-action@v12
      with:
        name: ihaskell
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - run: |
        nix build .#${{matrix.executable}}

    - run: |
        nix-shell \
        -I nixpkgs=https://github.com/NixOS/nixpkgs/tarball/nixos-23.05 \
        -p jq --run \
        'test/acceptance.nbconvert.sh result/bin/jupyter nbconvert'
