name: Nix

on:
  schedule:
  - cron: '0 2 * * *'
  push:
    paths-ignore:
    - 'demo/**'
    - 'docker/**'
    - 'Dockerfile'
    - '.dockerignore'
    - '.ghci'
    - '.gitignore'
    - 'images/**'
    - 'notebooks/**'
    - 'README.md'
    - '*.yaml'
  pull_request:
    paths-ignore:
    - 'demo/**'
    - 'docker/**'
    - 'Dockerfile'
    - '.dockerignore'
    - '.ghci'
    - '.gitignore'
    - 'images/**'
    - 'notebooks/**'
    - 'README.md'
    - '*.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - ihaskell-env-ghc810
        - ihaskell-env-ghc90
        - ihaskell-env-ghc92
        - ihaskell-env-ghc94
        - ihaskell-env-ghc96
        - ihaskell-env-ghc98

    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v22
      with:
        install_url: https://releases.nixos.org/nix/nix-2.13.3/install

    - uses: cachix/cachix-action@v12
      with:
        name: ihaskell
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Build environment ${{matrix.env}}
      run: |
        nix build .#${{matrix.env}}

    - name: Check acceptance test for ${{matrix.env}}
      run: |
        nix build .#checks.x86_64-linux.${{matrix.env}} -L
