name: Nix

on:
  workflow_dispatch:
  schedule:
  - cron: '0 2 * * *'
  push:
    paths-ignore:
    - 'demo/**'
    - 'docker/**'
    - 'Dockerfile'
    - '.dockerignore'
    - '.ghci'
    - '.gitignore'
    - 'images/**'
    - 'notebooks/**'
    - 'stack/**'
    - 'README.md'
    - '*.yaml'
  pull_request:
    paths-ignore:
    - 'demo/**'
    - 'docker/**'
    - 'Dockerfile'
    - '.dockerignore'
    - '.ghci'
    - '.gitignore'
    - 'images/**'
    - 'notebooks/**'
    - 'stack/**'
    - 'README.md'
    - '*.yaml'

jobs:
  build:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    name: "${{matrix.env.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - name: ihaskell-env-ghc90
        - name: ihaskell-env-ghc92
        - name: ihaskell-env-ghc94
        - name: ihaskell-env-ghc96
        - name: ihaskell-env-ghc98

        - name: ihaskell-env-display-ghc90
        - name: ihaskell-env-display-ghc92
        - name: ihaskell-env-display-ghc94
        - name: ihaskell-env-display-ghc96
        - name: ihaskell-env-display-ghc98

    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v22
      with:
        install_url: https://releases.nixos.org/nix/nix-2.19.2/install

    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: "Build environment ${{matrix.env.name}}"
      run: |
        nix build .#${{matrix.env.name}}

    - name: Check acceptance test for ${{matrix.env.name}}
      # Disable GHC 9.8 here since we don't have hlint support yet
      # Also, don't bother running it with the display envs since we already run it with the
      # basic envs, and it doesn't test any display stuff.
      if: ${{ !contains(fromJSON('["ihaskell-env-ghc98"]'), matrix.env.name) && !contains(matrix.env.name, fromJSON('"display"')) }}
      run: |
        nix build .#checks.x86_64-linux.${{matrix.env.name}} -L
