name: Nix

on:
  workflow_dispatch:
  schedule:
  - cron: '0 2 * * *'
  push:
    paths-ignore:
    - 'demo/**'
    - 'docker/**'
    - 'Dockerfile'
    - '.dockerignore'
    - '.ghci'
    - '.gitignore'
    - 'images/**'
    - 'notebooks/**'
    - 'stack/**'
    - 'README.md'
    - '*.yaml'
  pull_request:
    paths-ignore:
    - 'demo/**'
    - 'docker/**'
    - 'Dockerfile'
    - '.dockerignore'
    - '.ghci'
    - '.gitignore'
    - 'images/**'
    - 'notebooks/**'
    - 'stack/**'
    - 'README.md'
    - '*.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    name: "${{matrix.env.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - name: ihaskell-env-ghc90
        - name: ihaskell-env-ghc92
        - name: ihaskell-env-ghc94
        - name: ihaskell-env-ghc96
        - name: ihaskell-env-ghc98
        - name: ihaskell-env-ghc910
        - name: ihaskell-env-ghc912

        - name: ihaskell-env-display-ghc90
        - name: ihaskell-env-display-ghc92
        - name: ihaskell-env-display-ghc94
        - name: ihaskell-env-display-ghc96
        - name: ihaskell-env-display-ghc98
        - name: ihaskell-env-display-ghc910
        - name: ihaskell-env-display-ghc912

    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v22
      with:
        install_url: https://releases.nixos.org/nix/nix-2.22.1/install

    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: "Build environment ${{matrix.env.name}}"
      run: |
        nix build .#${{matrix.env.name}}

    - name: Check acceptance test for ${{matrix.env}}
      # Don't bother running it with the display envs since we already run it
      # with the basic envs, and it doesn't test any display stuff.
      if: ${{ !(contains(matrix.env, fromJSON('"display"'))) }}
      run: |
        nix build .#checks.x86_64-linux.${{matrix.env.name}} -L
